Add github oauth2
Meet-Coder-Study/study-platform-backend pull request #17
Opened 2021-01-31 03:11 UTC by cwJohnPark

2021-01-31 07:02 UTC, ksy90101 requested changes
일단 1차적으로 간단한 피드백 남겼습니다.
수정 하신 후 다시 리뷰 요청 보내면 확인할꼐요! (실행은 그때 확인할께요!)

2021-01-31 07:02 UTC, ksy90101 commented on build.gradle
> +    compile group: 'org.webjars', name: 'webjars-locator-core'
이부분은 필요 없을꺼같은데.. 테스트 때문인거 같긴 한데.. ㅎ_ㅎ

2021-01-31 07:02 UTC, ksy90101 commented on src/main/java/com/study/platform/member/domain/MemberController.java
> +	@GetMapping("/member")
REST API는 복수형으로 사용합니다~
```suggestion
	@GetMapping("/members")
```
가 더 좋을거 같아요.

2021-01-31 07:02 UTC, ksy90101 commented on src/main/java/com/study/platform/security/WebSecurityConfig.java
> +            .authorizeRequests(a -> a
더 의미있는 변수가 있지 않을까요?
```suggestion
            .authorizeRequests(request -> request
```

2021-01-31 07:02 UTC, ksy90101 commented on src/main/java/com/study/platform/security/WebSecurityConfig.java
> +            .exceptionHandling(e -> e
여기도 더 의미잇는 변수가 잇지 않을까요?
```suggestion
            .exceptionHandling(exception -> exception
```

2021-01-31 07:02 UTC, ksy90101 commented on src/main/java/com/study/platform/security/WebSecurityConfig.java
> +                .logoutSuccessUrl("/").permitAll())
```suggestion
            .logout(request -> request
                .logoutSuccessUrl("/").permitAll())
```

2021-01-31 07:02 UTC, ksy90101 commented on src/main/resources/static/index.html
> +<!doctype html>
Merge할때 이 페이지는 없어도 될거 같아요.
REST API를 사용할거기 때문에 굳이 ㅎㅎ

2021-01-31 07:07 UTC, rockjoon approved these changes

2021-01-31 08:34 UTC, rockjoon commented on src/main/java/com/study/platform/security/WebSecurityConfig.java
> +            .authorizeRequests(a -> a
개인적으로 람다 변수는 쪼금만 길어져도 가독성이 급격히 떨어지기 때문에 간결한게 더 좋다고 생각합니당.
(그리고 타입이 워낙 한정적이라 의미도 쉽게 파악할 수 있구요)

혹시 몰라서 람다 naming convention을 찾아봤는데 아직 이렇다할 스탠다드는 없는 것 같네용

다들 어떻게 생각하시나요?

2021-02-02 13:01 UTC, cwJohnPark commented on build.gradle
> +    compile group: 'org.webjars', name: 'webjars-locator-core'
네 테스트 용이에요 빼요 ?

2021-02-02 13:33 UTC, merged